/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#2e353f',
        'surface-bright': '#333a44',
        'surface-container-low': '#151c25',
        'on-surface-variant': '#e9bcb6',
        'on-background': '#dce3f0',
        'surface-container': '#192029',
        'surface-dim': '#0d141d',
        background: '#0d141d',
        outline: '#af8782',
        'surface-tint': '#ffb4aa',
        'on-secondary': '#3f2e00',
        'on-surface': '#dce3f0',
        'secondary-fixed-dim': '#fabd00',
        'on-error': '#690005',
        'tertiary-container': '#737272',
        error: '#ffb4ab',
        'primary-fixed': '#ffdad5',
        'surface-container-high': '#232a34',
        'on-error-container': '#ffdad6',
        tertiary: '#c8c6c5',
        'inverse-on-surface': '#2a313b',
        'surface-container-highest': '#2e353f',
        'on-secondary-fixed': '#261a00',
        'surface-container-lowest': '#080f17',
        'on-primary-container': '#fff7f6',
        primary: '#ffb4aa',
        'on-secondary-container': '#6a4e00',
        'secondary-container': '#fabd00',
        'primary-fixed-dim': '#ffb4aa',
        'on-tertiary-container': '#fbf8f8',
        'error-container': '#93000a',
        'on-primary': '#690003',
        'on-primary-fixed-variant': '#930007',
        'outline-variant': '#5e3f3b',
        'on-primary-fixed': '#410001',
        surface: '#0d141d',
        'secondary-fixed': '#ffdf9e',
        'inverse-surface': '#dce3f0',
        'primary-container': '#e50914',
        'inverse-primary': '#c0000c',
        secondary: '#ffdf9e',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'container-max': '1440px',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}