// <auto-generated />
using CineCraft.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CineCraft.Api.Data.Migrations
{
    [DbContext(typeof(CineCraftContext))]
    partial class CineCraftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CineCraft.Api.Models.CompartirReseniaUsuario", b =>
                {
                    b.Property<int>("ReseniaId")
                        .HasColumnType("integer")
                        .HasColumnName("resenia_id");

                    b.Property<int>("UsuarioRemitenteId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_remitente_id");

                    b.Property<int>("UsuarioDestinatarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_destinatario_id");

                    b.HasKey("ReseniaId", "UsuarioRemitenteId", "UsuarioDestinatarioId");

                    b.HasIndex("UsuarioDestinatarioId");

                    b.HasIndex("UsuarioRemitenteId");

                    b.ToTable("compartir_resenia_usuario", (string)null);
                });

            modelBuilder.Entity("CineCraft.Api.Models.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("etiqueta", (string)null);
                });

            modelBuilder.Entity("CineCraft.Api.Models.Resenia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archivada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("archivada");

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<bool>("Destacada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("destacada");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("integer")
                        .HasColumnName("etiqueta_id");

                    b.Property<string>("TituloPelicula")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo_pelicula");

                    b.Property<int>("UsuarioAutorId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_autor_id");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("UsuarioAutorId");

                    b.ToTable("resenia", null, t =>
                        {
                            t.HasCheckConstraint("CK_resenia_calificacion", "calificacion >= 0 AND calificacion <= 10");
                        });
                });

            modelBuilder.Entity("CineCraft.Api.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("CineCraft.Api.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("solicitud", (string)null);
                });

            modelBuilder.Entity("CineCraft.Api.Models.SolicitudStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("solicitud_status", (string)null);
                });

            modelBuilder.Entity("CineCraft.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int?>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("SolicitudId")
                        .IsUnique()
                        .HasFilter("solicitud_id IS NOT NULL");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("CineCraft.Api.Models.CompartirReseniaUsuario", b =>
                {
                    b.HasOne("CineCraft.Api.Models.Resenia", "Resenia")
                        .WithMany("Compartidos")
                        .HasForeignKey("ReseniaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineCraft.Api.Models.Usuario", "UsuarioDestinatario")
                        .WithMany("ReseniasRecibidas")
                        .HasForeignKey("UsuarioDestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineCraft.Api.Models.Usuario", "UsuarioRemitente")
                        .WithMany("ReseniasEnviadas")
                        .HasForeignKey("UsuarioRemitenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resenia");

                    b.Navigation("UsuarioDestinatario");

                    b.Navigation("UsuarioRemitente");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Etiqueta", b =>
                {
                    b.HasOne("CineCraft.Api.Models.Usuario", "Usuario")
                        .WithMany("Etiquetas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Resenia", b =>
                {
                    b.HasOne("CineCraft.Api.Models.Etiqueta", "Etiqueta")
                        .WithMany("Resenias")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineCraft.Api.Models.Usuario", "UsuarioAutor")
                        .WithMany("Resenias")
                        .HasForeignKey("UsuarioAutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("UsuarioAutor");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Solicitud", b =>
                {
                    b.HasOne("CineCraft.Api.Models.SolicitudStatus", "Status")
                        .WithMany("Solicitudes")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Usuario", b =>
                {
                    b.HasOne("CineCraft.Api.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineCraft.Api.Models.Solicitud", "Solicitud")
                        .WithOne("Usuario")
                        .HasForeignKey("CineCraft.Api.Models.Usuario", "SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rol");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Etiqueta", b =>
                {
                    b.Navigation("Resenias");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Resenia", b =>
                {
                    b.Navigation("Compartidos");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Solicitud", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineCraft.Api.Models.SolicitudStatus", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("CineCraft.Api.Models.Usuario", b =>
                {
                    b.Navigation("Etiquetas");

                    b.Navigation("Resenias");

                    b.Navigation("ReseniasEnviadas");

                    b.Navigation("ReseniasRecibidas");
                });
#pragma warning restore 612, 618
        }
    }
}
